<?php
/**
 * DistrictsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Edlink Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdLink\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EdLink\ApiException;
use EdLink\Configuration;
use EdLink\HeaderSelector;
use EdLink\ObjectSerializer;

/**
 * DistrictsApi Class Doc Comment
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DistrictsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'districtsControllerFetchDistrictForIntegration' => [
            'application/json',
        ],
        'districtsControllerListAdministratorsForDistrict' => [
            'application/json',
        ],
        'districtsControllerListDistrictsForIntegration' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation districtsControllerFetchDistrictForIntegration
     *
     * Fetch an individual district by ID
     *
     * @param  string $district_id district_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerFetchDistrictForIntegration'] to see the possible values for this operation
     *
     * @throws \EdLink\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response
     */
    public function districtsControllerFetchDistrictForIntegration($district_id, string $contentType = self::contentTypes['districtsControllerFetchDistrictForIntegration'][0])
    {
        list($response) = $this->districtsControllerFetchDistrictForIntegrationWithHttpInfo($district_id, $contentType);
        return $response;
    }

    /**
     * Operation districtsControllerFetchDistrictForIntegrationWithHttpInfo
     *
     * Fetch an individual district by ID
     *
     * @param  string $district_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerFetchDistrictForIntegration'] to see the possible values for this operation
     *
     * @throws \EdLink\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function districtsControllerFetchDistrictForIntegrationWithHttpInfo($district_id, string $contentType = self::contentTypes['districtsControllerFetchDistrictForIntegration'][0])
    {
        $request = $this->districtsControllerFetchDistrictForIntegrationRequest($district_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation districtsControllerFetchDistrictForIntegrationAsync
     *
     * Fetch an individual district by ID
     *
     * @param  string $district_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerFetchDistrictForIntegration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function districtsControllerFetchDistrictForIntegrationAsync($district_id, string $contentType = self::contentTypes['districtsControllerFetchDistrictForIntegration'][0])
    {
        return $this->districtsControllerFetchDistrictForIntegrationAsyncWithHttpInfo($district_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation districtsControllerFetchDistrictForIntegrationAsyncWithHttpInfo
     *
     * Fetch an individual district by ID
     *
     * @param  string $district_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerFetchDistrictForIntegration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function districtsControllerFetchDistrictForIntegrationAsyncWithHttpInfo($district_id, string $contentType = self::contentTypes['districtsControllerFetchDistrictForIntegration'][0])
    {
        $returnType = '\EdLink\Model\DistrictsControllerFetchDistrictForIntegration200Response';
        $request = $this->districtsControllerFetchDistrictForIntegrationRequest($district_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'districtsControllerFetchDistrictForIntegration'
     *
     * @param  string $district_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerFetchDistrictForIntegration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function districtsControllerFetchDistrictForIntegrationRequest($district_id, string $contentType = self::contentTypes['districtsControllerFetchDistrictForIntegration'][0])
    {

        // verify the required parameter 'district_id' is set
        if ($district_id === null || (is_array($district_id) && count($district_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $district_id when calling districtsControllerFetchDistrictForIntegration'
            );
        }


        $resourcePath = '/api/v2/graph/districts/{district_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($district_id !== null) {
            $resourcePath = str_replace(
                '{' . 'district_id' . '}',
                ObjectSerializer::toPathValue($district_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation districtsControllerListAdministratorsForDistrict
     *
     * List all administrators for a district.
     *
     * @param  string $district_id district_id (required)
     * @param  mixed $last Backwards from the &#x60;$before&#x60; parameter (or the end of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $before The last document ID, to be used in conjunction with &#x60;$last&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $first Forwards from the &#x60;$after&#x60; parameter (or the beginning of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $after The last document ID, to be used in conjunction with &#x60;$first&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  string $filter A stringified set of JSON-encoded filters. For more information, refer to the [Result filtering documentation](https://ed.link/docs/guides/v2.0/filtering-results) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListAdministratorsForDistrict'] to see the possible values for this operation
     *
     * @throws \EdLink\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response
     */
    public function districtsControllerListAdministratorsForDistrict($district_id, $last = null, $before = null, $first = null, $after = null, $filter = null, string $contentType = self::contentTypes['districtsControllerListAdministratorsForDistrict'][0])
    {
        list($response) = $this->districtsControllerListAdministratorsForDistrictWithHttpInfo($district_id, $last, $before, $first, $after, $filter, $contentType);
        return $response;
    }

    /**
     * Operation districtsControllerListAdministratorsForDistrictWithHttpInfo
     *
     * List all administrators for a district.
     *
     * @param  string $district_id (required)
     * @param  mixed $last Backwards from the &#x60;$before&#x60; parameter (or the end of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $before The last document ID, to be used in conjunction with &#x60;$last&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $first Forwards from the &#x60;$after&#x60; parameter (or the beginning of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $after The last document ID, to be used in conjunction with &#x60;$first&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  string $filter A stringified set of JSON-encoded filters. For more information, refer to the [Result filtering documentation](https://ed.link/docs/guides/v2.0/filtering-results) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListAdministratorsForDistrict'] to see the possible values for this operation
     *
     * @throws \EdLink\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function districtsControllerListAdministratorsForDistrictWithHttpInfo($district_id, $last = null, $before = null, $first = null, $after = null, $filter = null, string $contentType = self::contentTypes['districtsControllerListAdministratorsForDistrict'][0])
    {
        $request = $this->districtsControllerListAdministratorsForDistrictRequest($district_id, $last, $before, $first, $after, $filter, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation districtsControllerListAdministratorsForDistrictAsync
     *
     * List all administrators for a district.
     *
     * @param  string $district_id (required)
     * @param  mixed $last Backwards from the &#x60;$before&#x60; parameter (or the end of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $before The last document ID, to be used in conjunction with &#x60;$last&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $first Forwards from the &#x60;$after&#x60; parameter (or the beginning of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $after The last document ID, to be used in conjunction with &#x60;$first&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  string $filter A stringified set of JSON-encoded filters. For more information, refer to the [Result filtering documentation](https://ed.link/docs/guides/v2.0/filtering-results) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListAdministratorsForDistrict'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function districtsControllerListAdministratorsForDistrictAsync($district_id, $last = null, $before = null, $first = null, $after = null, $filter = null, string $contentType = self::contentTypes['districtsControllerListAdministratorsForDistrict'][0])
    {
        return $this->districtsControllerListAdministratorsForDistrictAsyncWithHttpInfo($district_id, $last, $before, $first, $after, $filter, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation districtsControllerListAdministratorsForDistrictAsyncWithHttpInfo
     *
     * List all administrators for a district.
     *
     * @param  string $district_id (required)
     * @param  mixed $last Backwards from the &#x60;$before&#x60; parameter (or the end of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $before The last document ID, to be used in conjunction with &#x60;$last&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $first Forwards from the &#x60;$after&#x60; parameter (or the beginning of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $after The last document ID, to be used in conjunction with &#x60;$first&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  string $filter A stringified set of JSON-encoded filters. For more information, refer to the [Result filtering documentation](https://ed.link/docs/guides/v2.0/filtering-results) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListAdministratorsForDistrict'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function districtsControllerListAdministratorsForDistrictAsyncWithHttpInfo($district_id, $last = null, $before = null, $first = null, $after = null, $filter = null, string $contentType = self::contentTypes['districtsControllerListAdministratorsForDistrict'][0])
    {
        $returnType = '\EdLink\Model\DistrictsControllerListAdministratorsForDistrict200Response';
        $request = $this->districtsControllerListAdministratorsForDistrictRequest($district_id, $last, $before, $first, $after, $filter, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'districtsControllerListAdministratorsForDistrict'
     *
     * @param  string $district_id (required)
     * @param  mixed $last Backwards from the &#x60;$before&#x60; parameter (or the end of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $before The last document ID, to be used in conjunction with &#x60;$last&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $first Forwards from the &#x60;$after&#x60; parameter (or the beginning of the dataset if not specified),how many documents to fetch. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  mixed $after The last document ID, to be used in conjunction with &#x60;$first&#x60;. For more information, refer to the [Pagination documentation](https://ed.link/docs/guides/v2.0/paginated-requests) (optional)
     * @param  string $filter A stringified set of JSON-encoded filters. For more information, refer to the [Result filtering documentation](https://ed.link/docs/guides/v2.0/filtering-results) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListAdministratorsForDistrict'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function districtsControllerListAdministratorsForDistrictRequest($district_id, $last = null, $before = null, $first = null, $after = null, $filter = null, string $contentType = self::contentTypes['districtsControllerListAdministratorsForDistrict'][0])
    {

        // verify the required parameter 'district_id' is set
        if ($district_id === null || (is_array($district_id) && count($district_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $district_id when calling districtsControllerListAdministratorsForDistrict'
            );
        }

        if ($last !== null && $last > 10000) {
            throw new \InvalidArgumentException('invalid value for "$last" when calling DistrictsApi.districtsControllerListAdministratorsForDistrict, must be smaller than or equal to 10000.');
        }
        if ($last !== null && $last < 1) {
            throw new \InvalidArgumentException('invalid value for "$last" when calling DistrictsApi.districtsControllerListAdministratorsForDistrict, must be bigger than or equal to 1.');
        }
        

        if ($first !== null && $first > 10000) {
            throw new \InvalidArgumentException('invalid value for "$first" when calling DistrictsApi.districtsControllerListAdministratorsForDistrict, must be smaller than or equal to 10000.');
        }
        if ($first !== null && $first < 1) {
            throw new \InvalidArgumentException('invalid value for "$first" when calling DistrictsApi.districtsControllerListAdministratorsForDistrict, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/api/v2/graph/districts/{district_id}/administrators';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $last,
            '$last', // param base name
            'mixed', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $before,
            '$before', // param base name
            'mixed', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $first,
            '$first', // param base name
            'mixed', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $after,
            '$after', // param base name
            'mixed', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($district_id !== null) {
            $resourcePath = str_replace(
                '{' . 'district_id' . '}',
                ObjectSerializer::toPathValue($district_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation districtsControllerListDistrictsForIntegration
     *
     * List all districts for this integration.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListDistrictsForIntegration'] to see the possible values for this operation
     *
     * @throws \EdLink\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response
     */
    public function districtsControllerListDistrictsForIntegration(string $contentType = self::contentTypes['districtsControllerListDistrictsForIntegration'][0])
    {
        list($response) = $this->districtsControllerListDistrictsForIntegrationWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation districtsControllerListDistrictsForIntegrationWithHttpInfo
     *
     * List all districts for this integration.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListDistrictsForIntegration'] to see the possible values for this operation
     *
     * @throws \EdLink\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function districtsControllerListDistrictsForIntegrationWithHttpInfo(string $contentType = self::contentTypes['districtsControllerListDistrictsForIntegration'][0])
    {
        $request = $this->districtsControllerListDistrictsForIntegrationRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation districtsControllerListDistrictsForIntegrationAsync
     *
     * List all districts for this integration.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListDistrictsForIntegration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function districtsControllerListDistrictsForIntegrationAsync(string $contentType = self::contentTypes['districtsControllerListDistrictsForIntegration'][0])
    {
        return $this->districtsControllerListDistrictsForIntegrationAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation districtsControllerListDistrictsForIntegrationAsyncWithHttpInfo
     *
     * List all districts for this integration.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListDistrictsForIntegration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function districtsControllerListDistrictsForIntegrationAsyncWithHttpInfo(string $contentType = self::contentTypes['districtsControllerListDistrictsForIntegration'][0])
    {
        $returnType = '\EdLink\Model\DistrictsControllerListDistrictsForIntegration200Response';
        $request = $this->districtsControllerListDistrictsForIntegrationRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'districtsControllerListDistrictsForIntegration'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['districtsControllerListDistrictsForIntegration'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function districtsControllerListDistrictsForIntegrationRequest(string $contentType = self::contentTypes['districtsControllerListDistrictsForIntegration'][0])
    {


        $resourcePath = '/api/v2/graph/districts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
