<?php
/**
 * Demographics
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Edlink Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdLink\Model;

use ArrayAccess;
use EdLink\ObjectSerializer;

/**
 * Demographics Class Doc Comment
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Demographics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Demographics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'birthday' => '\DateTime',
        'gender' => 'string',
        'residence_status' => 'string',
        'english_language_learner' => 'bool',
        'country_of_birth' => 'string',
        'state_of_birth' => 'string',
        'city_of_birth' => 'string',
        'hispanic_or_latino_ethnicity' => 'bool',
        'races' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'birthday' => 'date-time',
        'gender' => null,
        'residence_status' => null,
        'english_language_learner' => null,
        'country_of_birth' => null,
        'state_of_birth' => null,
        'city_of_birth' => null,
        'hispanic_or_latino_ethnicity' => null,
        'races' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'birthday' => 'birthday',
        'gender' => 'gender',
        'residence_status' => 'residence_status',
        'english_language_learner' => 'english_language_learner',
        'country_of_birth' => 'country_of_birth',
        'state_of_birth' => 'state_of_birth',
        'city_of_birth' => 'city_of_birth',
        'hispanic_or_latino_ethnicity' => 'hispanic_or_latino_ethnicity',
        'races' => 'races'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'birthday' => 'setBirthday',
        'gender' => 'setGender',
        'residence_status' => 'setResidenceStatus',
        'english_language_learner' => 'setEnglishLanguageLearner',
        'country_of_birth' => 'setCountryOfBirth',
        'state_of_birth' => 'setStateOfBirth',
        'city_of_birth' => 'setCityOfBirth',
        'hispanic_or_latino_ethnicity' => 'setHispanicOrLatinoEthnicity',
        'races' => 'setRaces'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'birthday' => 'getBirthday',
        'gender' => 'getGender',
        'residence_status' => 'getResidenceStatus',
        'english_language_learner' => 'getEnglishLanguageLearner',
        'country_of_birth' => 'getCountryOfBirth',
        'state_of_birth' => 'getStateOfBirth',
        'city_of_birth' => 'getCityOfBirth',
        'hispanic_or_latino_ethnicity' => 'getHispanicOrLatinoEthnicity',
        'races' => 'getRaces'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const GENDER_MALE = 'male';
    const GENDER_FEMALE = 'female';
    const GENDER_OTHER = 'other';
    const RESIDENCE_STATUS__01652 = '01652';
    const RESIDENCE_STATUS__01653 = '01653';
    const RESIDENCE_STATUS__01654 = '01654';
    const RESIDENCE_STATUS__01655 = '01655';
    const RESIDENCE_STATUS__01656 = '01656';
    const RACES_AMERICAN_INDIAN_OR_ALASKA_NATIVE = 'american-indian-or-alaska-native';
    const RACES_ASIAN = 'asian';
    const RACES_BLACK_OR_AFRICAN_AMERICAN = 'black-or-african-american';
    const RACES_NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = 'native-hawaiian-or-other-pacific-islander';
    const RACES_WHITE = 'white';



    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderAllowableValues()
    {
        return [
            self::GENDER_MALE,
            self::GENDER_FEMALE,
            self::GENDER_OTHER,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getResidenceStatusAllowableValues()
    {
        return [
            self::RESIDENCE_STATUS__01652,
            self::RESIDENCE_STATUS__01653,
            self::RESIDENCE_STATUS__01654,
            self::RESIDENCE_STATUS__01655,
            self::RESIDENCE_STATUS__01656,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRacesAllowableValues()
    {
        return [
            self::RACES_AMERICAN_INDIAN_OR_ALASKA_NATIVE,
            self::RACES_ASIAN,
            self::RACES_BLACK_OR_AFRICAN_AMERICAN,
            self::RACES_NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER,
            self::RACES_WHITE,
        ];
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['birthday'] = $data['birthday'] ?? null;
        $this->container['gender'] = $data['gender'] ?? null;
        $this->container['residence_status'] = $data['residence_status'] ?? null;
        $this->container['english_language_learner'] = $data['english_language_learner'] ?? null;
        $this->container['country_of_birth'] = $data['country_of_birth'] ?? null;
        $this->container['state_of_birth'] = $data['state_of_birth'] ?? null;
        $this->container['city_of_birth'] = $data['city_of_birth'] ?? null;
        $this->container['hispanic_or_latino_ethnicity'] = $data['hispanic_or_latino_ethnicity'] ?? null;
        $this->container['races'] = $data['races'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['birthday'] === null) {
            $invalidProperties[] = "'birthday' can't be null";
        }
        if ($this->container['gender'] === null) {
            $invalidProperties[] = "'gender' can't be null";
        }
        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($this->container['gender']) && !in_array($this->container['gender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gender', must be one of '%s'",
                $this->container['gender'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['residence_status'] === null) {
            $invalidProperties[] = "'residence_status' can't be null";
        }
        $allowedValues = $this->getResidenceStatusAllowableValues();
        if (!is_null($this->container['residence_status']) && !in_array($this->container['residence_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'residence_status', must be one of '%s'",
                $this->container['residence_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['english_language_learner'] === null) {
            $invalidProperties[] = "'english_language_learner' can't be null";
        }
        if ($this->container['country_of_birth'] === null) {
            $invalidProperties[] = "'country_of_birth' can't be null";
        }
        if ($this->container['state_of_birth'] === null) {
            $invalidProperties[] = "'state_of_birth' can't be null";
        }
        if ($this->container['city_of_birth'] === null) {
            $invalidProperties[] = "'city_of_birth' can't be null";
        }
        if ($this->container['hispanic_or_latino_ethnicity'] === null) {
            $invalidProperties[] = "'hispanic_or_latino_ethnicity' can't be null";
        }
        if ($this->container['races'] === null) {
            $invalidProperties[] = "'races' can't be null";
        }
        $allowedValues = $this->getRacesAllowableValues();
        if (!is_null($this->container['races']) && array_diff($this->container['races'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'races', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets birthday
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        return $this->container['birthday'];
    }

    /**
     * Sets birthday
     *
     * @param \DateTime $birthday birthday
     *
     * @return self
     */
    public function setBirthday($birthday)
    {
        $this->container['birthday'] = $birthday;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string $gender gender
     *
     * @return self
     */
    public function setGender($gender)
    {
        $allowedValues = $this->getGenderAllowableValues();
        if (!in_array($gender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gender', must be one of '%s'",
                    $gender,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets residence_status
     *
     * @return string
     */
    public function getResidenceStatus()
    {
        return $this->container['residence_status'];
    }

    /**
     * Sets residence_status
     *
     * @param string $residence_status [https://ed.link/docs/api/v2.0/models/external/enums/public-school-residence-status](https://ed.link/docs/api/v2.0/models/external/enums/public-school-residence-status)
     *
     * @return self
     */
    public function setResidenceStatus($residence_status)
    {
        $allowedValues = $this->getResidenceStatusAllowableValues();
        if (!in_array($residence_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'residence_status', must be one of '%s'",
                    $residence_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['residence_status'] = $residence_status;

        return $this;
    }

    /**
     * Gets english_language_learner
     *
     * @return bool
     */
    public function getEnglishLanguageLearner()
    {
        return $this->container['english_language_learner'];
    }

    /**
     * Sets english_language_learner
     *
     * @param bool $english_language_learner english_language_learner
     *
     * @return self
     */
    public function setEnglishLanguageLearner($english_language_learner)
    {
        $this->container['english_language_learner'] = $english_language_learner;

        return $this;
    }

    /**
     * Gets country_of_birth
     *
     * @return string
     */
    public function getCountryOfBirth()
    {
        return $this->container['country_of_birth'];
    }

    /**
     * Sets country_of_birth
     *
     * @param string $country_of_birth country_of_birth
     *
     * @return self
     */
    public function setCountryOfBirth($country_of_birth)
    {
        $this->container['country_of_birth'] = $country_of_birth;

        return $this;
    }

    /**
     * Gets state_of_birth
     *
     * @return string
     */
    public function getStateOfBirth()
    {
        return $this->container['state_of_birth'];
    }

    /**
     * Sets state_of_birth
     *
     * @param string $state_of_birth state_of_birth
     *
     * @return self
     */
    public function setStateOfBirth($state_of_birth)
    {
        $this->container['state_of_birth'] = $state_of_birth;

        return $this;
    }

    /**
     * Gets city_of_birth
     *
     * @return string
     */
    public function getCityOfBirth()
    {
        return $this->container['city_of_birth'];
    }

    /**
     * Sets city_of_birth
     *
     * @param string $city_of_birth city_of_birth
     *
     * @return self
     */
    public function setCityOfBirth($city_of_birth)
    {
        $this->container['city_of_birth'] = $city_of_birth;

        return $this;
    }

    /**
     * Gets hispanic_or_latino_ethnicity
     *
     * @return bool
     */
    public function getHispanicOrLatinoEthnicity()
    {
        return $this->container['hispanic_or_latino_ethnicity'];
    }

    /**
     * Sets hispanic_or_latino_ethnicity
     *
     * @param bool $hispanic_or_latino_ethnicity hispanic_or_latino_ethnicity
     *
     * @return self
     */
    public function setHispanicOrLatinoEthnicity($hispanic_or_latino_ethnicity)
    {
        $this->container['hispanic_or_latino_ethnicity'] = $hispanic_or_latino_ethnicity;

        return $this;
    }

    /**
     * Gets races
     *
     * @return string
     */
    public function getRaces()
    {
        return $this->container['races'];
    }

    /**
     * Sets races
     *
     * @param string[] $races races
     *
     * @return self
     */
    public function setRaces($races)
    {
        $allowedValues = $this->getRacesAllowableValues();
        if (array_diff($races, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'races', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['races'] = $races;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


