<?php
/**
 * CoursesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Edlink Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EdLink\Test\Api;

use \EdLink\Configuration;
use \EdLink\ApiException;
use \EdLink\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CoursesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CoursesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for coursesControllerFetchAgent
     *
     * Fetch an individual agent by ID.
     *
     */
    public function testCoursesControllerFetchAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for coursesControllerListClassesForCourse
     *
     * Fetch all classes for a specific course.
     *
     */
    public function testCoursesControllerListClassesForCourse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for coursesControllerListCourses
     *
     * List all courses for this integration.
     *
     */
    public function testCoursesControllerListCourses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
