<?php
/**
 * PeopleApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Edlink Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EdLink\Test\Api;

use \EdLink\Configuration;
use \EdLink\ApiException;
use \EdLink\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PeopleApiTest Class Doc Comment
 *
 * @category Class
 * @package  EdLink
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PeopleApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for peopleControllerFetchPersonForIntegration
     *
     * Fetch an individual person by ID.
     *
     */
    public function testPeopleControllerFetchPersonForIntegration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for peopleControllerListAgentsForPerson
     *
     * List all agents for an individual person.
     *
     */
    public function testPeopleControllerListAgentsForPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for peopleControllerListClassesForPerson
     *
     * List all classes for an individual person.
     *
     */
    public function testPeopleControllerListClassesForPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for peopleControllerListDistrictsForPerson
     *
     * List all districts for an individual person.
     *
     */
    public function testPeopleControllerListDistrictsForPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for peopleControllerListEnrollmentsForPerson
     *
     * List all enrollments for an individual person.
     *
     */
    public function testPeopleControllerListEnrollmentsForPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for peopleControllerListPeopleForIntegration
     *
     * List all people for this integration.
     *
     */
    public function testPeopleControllerListPeopleForIntegration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for peopleControllerListSchoolsForPerson
     *
     * List all schools for an individual person.
     *
     */
    public function testPeopleControllerListSchoolsForPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
